### ISSUE TITLE
安装求助

### ISSUE THREAD

**Issue by li7862756** [koolshare/rogsoft#1]
sh /tmp/softcenter/install.sh 就提示一个httpd 什么的 然后刷新页面没有看到软件中心 重启后网络能ping通 网页打不开了
酷容提示
设置已更新网页将进行刷新IP地址或端口已更改将断开与AC86U的连接 要设置设备要重新连接至无线网络并使用新的IP地址和端口
火狐 空白页

**Comment by sadoneli** [comment]
not released yet! 
btw, the software center can only working on specific firmware which is under testing now
