### ISSUE TITLE
kscore.sh 笔误

### ISSUE THREAD

**Issue by macdoor** [koolshare/rogsoft#10]
第18行
STARTCOMAND1=`cat /jffs/scripts/wan-start | grep "/koolshare/bin/ks-wan-start.sh start'"`

倒数第三个字符的单引号，似乎不应该有，现在这样会造成每次重启路由器都给 /jffs/scripts/wan-start 文件加一行 /koolshare/bin/ks-wan-start.sh start，最后会有很多行，启动时重复执行很多遍 ks-wan-start.sh start。

这个是否造成系统不稳定，我再测试一下

**Comment by sadoneli** [comment]
fixed
