### ISSUE TITLE
AC86U 开启SS+KCP后KCP一直未运行，国外PD

### ISSUE THREAD

**Issue by fatecele** [koolshare/rogsoft#15]
pc端参数使用kcptun正常，路由端ss页面填入127.0.0.1:1091，KCP加速页默认本地监听1091，服务器地址和端口均按服务器端信息填入，开启科学上网后显示kcptun未运行，求帮助，谢谢！

**Comment by sadoneli** [comment]
ss页面的ss帐号不要做更改，填写kcp页面就行了
