### ISSUE TITLE
SS一直无法工作

### ISSUE THREAD

**Issue by nickwoo8158** [koolshare/rogsoft#17]
一直无法连通国外

SS账号没有问题，搬瓦工上SSR服务端的版本是3.3.3，所有提示的troubleshooting的方法都试过了，刷的是3.8.1_2的固件，含泪跪求解决方法...

**Comment by nickwoo8158** [comment]
总结下昨天AC86U的SS不能用的问题， ss.jason里面的配置没有密码， Iptable的转发规则默认是用192.168.1.1而86默认分配的地址是50.1, 把这两个改了，把进程手工重启，不要用ui重启就搞定了...希望能帮助大家，研究了好久.. 麻烦大大下次把这个bug fix一下，谢谢了

**Comment by asmh1989** [comment]
你的问题, 我没遇到, 我这边是, 不管ss还是ssr, 国外连接老是奇怪的断开, 有时候通过修改dns方案又好了, 有时候就只能换服务器了, 老是不长久, 想用的时候要去重启下服务

**Comment by nickwoo8158** [comment]
我现在很稳定了，把脚本里面的base64_decode 变成 base64
-d就可以了，这个命令在ac86u上不工作，导致ss.json的密码是空的，iptable里面的转发ip 永远是 192.168.1.1,
下次release的时候可以帮忙fix一下，谢谢啦

2018-03-15 10:37 GMT+08:00 sun <notifications@github.com>:

**Comment by asmh1989** [comment]
@nickwoo8158  可以把修改的 提交上来吗, 我也来试试效果

**Comment by nickwoo8158** [comment]
我同事帮忙提交了代码 https://github.com/koolshare/koolshare.github.io/pull/804
