### ISSUE TITLE
SS-SERVER AC86u不稳定

### ISSUE THREAD

**Issue by kelvinfong13** [koolshare/rogsoft#19]
固件 384.4
软件中心1.2.5
SS-SERVER 二进制版本: 3.1.1
经常无法连入
要登入软件中心重启ss-server才能登入
但一段时间后又失效了
(流量消秏过频繁好像也会失效)

**Comment by sadoneli** [comment]
失效的时候看下iptables是什么情况
```iptablea -nvL -t nat```

**Comment by kelvinfong13** [comment]
以Windows的Shadowsocks连接 YouTube Twitch Bilibili 等网站SS-SERVER就会失效
AC86U的iptables情况
![image](https://user-images.githubusercontent.com/32491201/38042393-d94b14b4-32e6-11e8-8476-280532d2627a.png)

Shadowsocks 的记录
[2018-03-29 00:01:21] System.Net.Sockets.SocketException (0x80004005): 無法連線，因為目標電腦拒絕連線。
   於 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   於 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   於 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by sadoneli** [comment]
```iptables -nvL INPUT``
这个呢

还有系统日志也看看

**Comment by sadoneli** [comment]
这个问题，你加个虚拟内存应该就好了，90%确定

**Comment by sadoneli** [comment]
之前我也是遇到各种程序崩溃，内核报错，加了虚拟内存后一个都没问题了

**Comment by kelvinfong13** [comment]
虚拟内存一直都有挂载1G

**Comment by PlanetSider** [comment]
我也是这个问题，已经挂载了1G虚拟内存，SS服务器正常，但是用的时间长了，就连不上屏蔽网站，必须要进软件中心手动关闭再打开才可以访问屏蔽网站

**Comment by Lstoryc** [comment]
我也出现同样问题，求解
