### ISSUE TITLE
AC86U大陆白名单模式彻底失效

### ISSUE THREAD

**Issue by tongle99** [koolshare/rogsoft#26]
原本1.1.6版是只有在kcptun开启的情况下才会失效，现在1.2.0版不管开不开kcp都完全失效，感觉越升级bug越多啊……已经手动退回1.1.6

**Comment by bigpao88** [comment]
我也有同样情况，1.2.0游戏模式上不了外网，只有退回1.1.6

**Comment by sadoneli** [comment]
ss还是ssr？

**Comment by bigpao88** [comment]
测试YouTube，就是显示链接非私密链接

**Comment by sadoneli** [comment]
这个可能是shadowsocks-libev 3.1.3的问题，我观察下

**Comment by bigpao88** [comment]
有可能是我路由器设置问题。我用ea6900梅林固件试最新的插件，都是正常的。

**Comment by xuxin1988** [comment]
这个问题只在AC86和GT5300上才会有问题,其他ss版本是3.8.9的就没问题,我同样EA6400就是一点问题都没问题

**Comment by sadoneli** [comment]
找到了类似的问题
https://github.com/shadowsocks/shadowsocks-libev/issues/1917
https://github.com/shadowsocks/shadowsocks-libev/issues/1961
总结下来就是chnroute分流的不行，反而gfwlist可以
3.1.3的不行，低版本3.1.2可以

但是作者最后都归于dns污染问题

我测试了所有dns方案都是这样，准备吧服务器和客户端都回滚到3.1.2试试

但是还是想不通为什么同版本的ss-libev在其他机器上又没有问题

**Comment by sadoneli** [comment]
症状是访问一些国外需要翻墙的网站，会提示你的连接不是私密连接
![image](https://user-images.githubusercontent.com/10495520/38908987-35842c34-42f5-11e8-82ef-ed6d839754fa.png)

**Comment by bigpao88** [comment]
对的，但是好像只有384内核有这问题。老版本固件下就没问题。

**Comment by sadoneli** [comment]
![image](https://user-images.githubusercontent.com/10495520/38909067-934a05fa-42f5-11e8-8f6c-ebfbc0fd6c23.png)
但是我刚才访问google hk发现被解析到了facebook，所以还是只有怀疑dns污染上
只是不理解的是为什么同样DNS，在shadowsocksR-libev上就没有这个问题

**Comment by tongle99** [comment]
我所在的网络环境比较特殊，dns改成8.8.8.8后可以登录谷歌油管Facebook等网站，但仍然会出现这个问题；还有我尝试过381内核的1.1.6版，仍然无法使用kcptun

**Comment by bigpao88** [comment]
怎么可以把ss 3.1.3手动换回3.1.2呢？

**Comment by sadoneli** [comment]
@bigpao88 需要编译静态版本的二进制文件，放到/koolshare/bin下

**Comment by sadoneli** [comment]
1. 3.1.3不行,3.1.2没问题
2 ss-libev不行，ssr-libev没问题
3 dns解析走ss服务器转发不行，其它去除dns污染的如cdns，不走服务器转发的也不行

这样排除下来确实像是3.1.3的问题，但是作者那边两个issue给出的答案都是DNS污染问题，我自己这里用dns2socks走服务器转发确实也遇到了google解析到了facebook的ip

现在我需要
1. 进一步确认是否版本问题
2. 确认dns污染来源

**Comment by bigpao88** [comment]
好的，大神辛苦了，我先用老版本坚持一下

**Comment by sadoneli** [comment]
1.1.6 原版ss，大陆白名单是完全正常的吧，不需要添加黑名单才能访问吧

**Comment by tongle99** [comment]
是的，完全正常，但是kcptun不正常，所有dns模式都无法使用

**Comment by sadoneli** [comment]
你服务器端的ss-libev的版本多少

**Comment by tongle99** [comment]
shadowsocks-libev 3.0.6

**Comment by sadoneli** [comment]
测试路由器端3.1.1，服务器3.1.3无问题

现在我尝试重新编译一下3.1.3的路由端二进制吧，真的是搞不懂什么原因

**Comment by sadoneli** [comment]
目前降级了3.1.2，服务器端仍然保持3.1.3，工作一切正常，给shadowsocks-libev作者提了issue，看进展了，我先观察一会儿，如果不行我会先推送回滚3.1.2

**Comment by tongle99** [comment]
感谢大神🙏

**Comment by sadoneli** [comment]
1.2.1版本应该修好了这个问题，请大家测试并反馈

**Comment by bigpao88** [comment]
感谢大神，1.2.1可以正常使用
