### ISSUE TITLE
86U签到插件系统记录时间不对 17点他日志是09点

### ISSUE THREAD

**Issue by aimei54** [koolshare/rogsoft#29]
1、好像软件中心的时间都不对！gangchongqig刚重启过
![qq 20180419172726](https://user-images.githubusercontent.com/28522328/38983452-f60f529c-43f6-11e8-8a06-e42adc4d6d27.png)
2、科学上网点关闭显示这样的，1.2.2版本吧卡死了 无法关闭……。
![image](https://user-images.githubusercontent.com/28522328/38983502-14ba741a-43f7-11e8-94c9-a2b2bcfacc96.png)

**Comment by aimei54** [comment]
各种崩溃……点什么按钮都没反应，然后后台显示这样的…… 86U
![image](https://user-images.githubusercontent.com/28522328/38983617-5344a250-43f7-11e8-97ad-5c3444d73a22.png)

**Comment by aimei54** [comment]
Apr 19 17:28:15 watchdog: restart httpd
Apr 19 17:28:15 rc_service: watchdog 972:notify_rc stop_httpd
Apr 19 17:28:15 rc_service: watchdog 972:notify_rc start_httpd
Apr 19 17:28:15 RT-AC86U: start https:8443
Apr 19 17:28:15 RT-AC86U: start httpd:80
Apr 19 17:29:01 kernel: pgd = ffffffc012586000
Apr 19 17:29:01 kernel: [00000068] *pgd=00000000119a3003, *pud=00000000119a3003, *pmd=00000000124fa003, *pte=0000000000000000
Apr 19 17:29:01 kernel: CPU: 0 PID: 3781 Comm: httpd Tainted: P           O    4.1.27 #2
Apr 19 17:29:01 kernel: Hardware name: Broadcom-v8A (DT)
Apr 19 17:29:01 kernel: task: ffffffc014b19500 ti: ffffffc01057c000 task.ti: ffffffc01057c000
Apr 19 17:29:01 kernel: PC is at 0xf6dcc294
Apr 19 17:29:01 kernel: LR is at 0x1635c
Apr 19 17:29:01 kernel: pc : [<00000000f6dcc294>] lr : [<000000000001635c>] pstate: 60000010
Apr 19 17:29:01 kernel: sp : 00000000ff8aac10
Apr 19 17:29:01 kernel: x12: 0000000000087688 
Apr 19 17:29:01 kernel: x11: 0000000000451040 x10: 00000000ff8aac90 
Apr 19 17:29:01 kernel: x9 : 000000000000000a x8 : 0000000000000000 
Apr 19 17:29:01 kernel: x7 : 0000000000452470 x6 : 00000000ff8aac90 
Apr 19 17:29:01 kernel: x5 : 00000000ff8ab790 x4 : 00000000000871e4 
Apr 19 17:29:01 kernel: x3 : 0000000000000000 x2 : 00000000f72e84c0 
Apr 19 17:29:01 kernel: x1 : 000000000000000c x0 : 0000000000000000 
Apr 19 17:29:15 watchdog: restart httpd
Apr 19 17:29:15 rc_service: watchdog 972:notify_rc stop_httpd
Apr 19 17:29:15 rc_service: watchdog 972:notify_rc start_httpd
Apr 19 17:29:15 RT-AC86U: start https:8443
Apr 19 17:29:15 RT-AC86U: start httpd:80
Apr 19 17:29:46 kernel: pgd = ffffffc0156c2000
Apr 19 17:29:46 kernel: [00000068] *pgd=0000000012586003, *pud=0000000012586003, *pmd=000000001250d003, *pte=0000000000000000
Apr 19 17:29:46 kernel: CPU: 1 PID: 3860 Comm: httpd Tainted: P           O    4.1.27 #2
Apr 19 17:29:46 kernel: Hardware name: Broadcom-v8A (DT)
Apr 19 17:29:46 kernel: task: ffffffc0192f60c0 ti: ffffffc009a18000 task.ti: ffffffc009a18000
Apr 19 17:29:46 kernel: PC is at 0xf6b42294
Apr 19 17:29:46 kernel: LR is at 0x1635c
Apr 19 17:29:46 kernel: pc : [<00000000f6b42294>] lr : [<000000000001635c>] pstate: 60000010
Apr 19 17:29:46 kernel: sp : 00000000ffaa93e0
Apr 19 17:29:46 kernel: x12: 0000000000087688 
Apr 19 17:29:46 kernel: x11: 0000000000208040 x10: 00000000ffaa9460 
Apr 19 17:29:46 kernel: x9 : 000000000000000a x8 : 0000000000000000 
Apr 19 17:29:46 kernel: x7 : 0000000000208d40 x6 : 00000000ffaa9460 
Apr 19 17:29:46 kernel: x5 : 00000000ffaa9f60 x4 : 00000000000871e4 
Apr 19 17:29:46 kernel: x3 : 0000000000000000 x2 : 00000000f705e4c0 
Apr 19 17:29:46 kernel: x1 : 000000000000000c x0 : 0000000000000000 
Apr 19 17:30:15 watchdog: restart httpd
Apr 19 17:30:15 rc_service: watchdog 972:notify_rc stop_httpd
Apr 19 17:30:15 rc_service: watchdog 972:notify_rc start_httpd
Apr 19 17:30:15 RT-AC86U: start https:8443
Apr 19 17:30:15 RT-AC86U: start httpd:80
Apr 19 17:30:46 kernel: pgd = ffffffc014879000
Apr 19 17:30:46 kernel: [00000068] *pgd=00000000115ee003, *pud=00000000115ee003, *pmd=000000000994c003, *pte=0000000000000000
Apr 19 17:30:46 kernel: CPU: 0 PID: 3925 Comm: httpd Tainted: P           O    4.1.27 #2
Apr 19 17:30:46 kernel: Hardware name: Broadcom-v8A (DT)
Apr 19 17:30:46 kernel: task: ffffffc01262e100 ti: ffffffc017254000 task.ti: ffffffc017254000
Apr 19 17:30:46 kernel: PC is at 0xf6f96294
Apr 19 17:30:46 kernel: LR is at 0x1635c
Apr 19 17:30:46 kernel: pc : [<00000000f6f96294>] lr : [<000000000001635c>] pstate: 60000010
Apr 19 17:30:46 kernel: sp : 00000000ffaa94d0
Apr 19 17:30:46 kernel: x12: 0000000000087688 
Apr 19 17:30:46 kernel: x11: 0000000000774040 x10: 00000000ffaa9550 
Apr 19 17:30:46 kernel: x9 : 000000000000000a x8 : 0000000000000000 
Apr 19 17:30:46 kernel: x7 : 0000000000774df0 x6 : 00000000ffaa9550 
Apr 19 17:30:46 kernel: x5 : 00000000ffaaa050 x4 : 00000000000871e4 
Apr 19 17:30:46 kernel: x3 : 0000000000000000 x2 : 00000000f74b24c0 
Apr 19 17:30:46 kernel: x1 : 000000000000000c x0 : 0000000000000000 
Apr 19 17:31:15 watchdog: restart httpd
Apr 19 17:31:15 rc_service: watchdog 972:notify_rc stop_httpd
Apr 19 17:31:15 rc_service: watchdog 972:notify_rc start_httpd
Apr 19 17:31:15 RT-AC86U: start https:8443
Apr 19 17:31:15 RT-AC86U: start httpd:80

这个是 假死日志……

**Comment by sadoneli** [comment]
1 时间是那样的，因为时区问题
2 上虚拟内存

**Comment by aimei54** [comment]
虚拟内存按照教程来过一次 可以。但是重启路由器就挂载不上了
![image](https://user-images.githubusercontent.com/28522328/38983769-be4419fa-43f7-11e8-9f90-29aef7f0aefd.png)

**Comment by sadoneli** [comment]
unmounted 没挂在上磁盘，你先解决下这个吧

**Comment by aimei54** [comment]
**现在**是ext3格式，我格式化成NFTS格式就能被挂载……然后按照教程手动移除挂载(命令不行)，格式化成ext3再继续按照教程成功挂载虚拟内存。
重启路由器就又挂载不上了，还得按照上面的来一遍很麻烦
每次虚拟内存就得这样来一遍。

**Comment by sadoneli** [comment]
你得把卷标给固定下来，不然每次重启可能卷标变了

**Comment by aimei54** [comment]
ssh打开了一直连不上……尴尬……86U好不稳定啊  
1.unmounted怎么解决啊，我之前试了mount /dev/sda /tmp/mnt/sda提示什么找不到目录文件啥的
2.卷标怎么固定啊求搜索的 关键词 或 语法

**Comment by aimei54** [comment]
![image](https://user-images.githubusercontent.com/28522328/38984946-ab3b62d4-43fa-11e8-9a96-36c4a5121f44.png)


df -h找不到
