### ISSUE TITLE
86U插件V2RAY在WS+PATH+TLS模式下无法工作

### ISSUE THREAD

**Issue by saturndu** [koolshare/rogsoft#31]
测试了其它模式都可以，就WS模式不能用

**Comment by sadoneli** [comment]
使用json配置能行吗？

**Comment by sadoneli** [comment]
我这里测试了两个这样的配置了，没问题的，你可以把json里关键信息改掉发上来我看看

**Comment by saturndu** [comment]
我自己用电脑V2RAYN和手机APP都是可以的。

**Comment by sadoneli** [comment]
另外我看你的path设定没有路径特征，假如你配置的是ws + tls +web的话，需要使用wd_header然后配置 伪装路径 和 伪装host，如果没有配置web的话，伪装路径应该留空就行了啊
