### ISSUE TITLE
ac86u挂了科学上网之后还是无法上外网

### ISSUE THREAD

**Issue by kuangshunran123** [koolshare/rogsoft#33]
ss测试过没有问题，路由器挂载之后上youtube可以加载出推荐页面，但是视频无法加载，推特能登录但是图片视频无法加载，求解
![screenshot_20180422-185247](https://user-images.githubusercontent.com/38612175/39094220-bbc0374a-465e-11e8-8960-4322ed053f9c.jpg)
![screenshot_20180422-185409](https://user-images.githubusercontent.com/38612175/39094222-c14022ca-465e-11e8-9307-925575710349.jpg)

**Comment by sadoneli** [comment]
请尝试游戏模式，youtube客户端可能会要求udp和tcp源一致
