### ISSUE TITLE
关于每次更新后国内DNS方案都会被重置为阿里DNS的问题

### ISSUE THREAD

**Issue by lbsnake** [koolshare/rogsoft#35]
目前用的是86U的版本，这个问题已经出现很久了。

**Comment by sadoneli** [comment]
https://github.com/koolshare/rogsoft/commit/7dd759c3d8e9ea049d5b164255142640ccacfe41
下次打包后更新应该就ok了

**Comment by lbsnake** [comment]
好的，再次感谢S大！！！

**Comment by chuan0932** [comment]
建议国内DNS在增加一个119.28.28.28

**Comment by sadoneli** [comment]
可以自己定义的
