### ISSUE TITLE
ac86u 软件中心空白

### ISSUE THREAD

**Issue by chylli** [koolshare/rogsoft#44]
原来好好的，今天重启了一次，发现变成空白了。版本号也忘了，好像是1.3.2，现在也不知道从哪里看版本号了。
固件是384.4

![qq 20180512150634](https://user-images.githubusercontent.com/22702/39957653-fe5fde28-5628-11e8-9cb2-abc05330bd8b.png)

**Comment by kelvinfong13** [comment]
挂上jffs

**Comment by KinsonSiu** [comment]
格式化jffs重启/断电重启

**Comment by chylli** [comment]
已经搞定，但原因是什么呢?

**Comment by marswow** [comment]
@chylli 无分区可用。jffs后就是格式化一个分区出来，有了分区就可以存储文件，然后在设置一个虚拟缓存爽歪歪~

**Comment by chylli** [comment]
@marswow 但为什么忽然无分区了呢?原来分好区了啊.想弄明白原理才能防止再次出现

**Comment by marswow** [comment]
@chylli 这个非专业人士真无法判断，出BUG了自己操作操作修复下就解决了。
