### ISSUE TITLE
ac86U 科学上网

### ISSUE THREAD

**Issue by chen510260x** [koolshare/rogsoft#45]
86U开启插件后，需要翻墙的网站经常进不去，但是我用SSR客户端是可以正常进入的。原因到底是什么？
插件内DNS设定老是让我翻不了墙，我直接改成了我需要的设定才能稍微翻一下，但还是不稳定

**Comment by yang05130** [comment]
看下插件里面的分流检测，换换dns试试。用插件的污染情况确实会比客户端严重。去年用了一年客户端，基本不出现dns污染。用路由上插件，刚开始不注意，就常出现，后面换了dns用，就能顶挺长时间的。据说目前是无解的
