### ISSUE TITLE
ss无法开启，提示未开启Enable JFFS custom scripts and configs

### ISSUE THREAD

**Issue by hk10424** [koolshare/rogsoft#54]
刷的 3.0.0.4.384_20648_koolshare，ss无法开启，提示未开启Enable JFFS custom scripts and configs

 【2018年06月09日

 21:35:15】: ======================= 梅林固件 - 【科学上网】 ========================
【2018年06月09日 21:35:15】:
【2018年06月09日 21:35:15】: ------------------------- 启动【科学上网】 -----------------------------
【2018年06月09日 21:35:15】: 删除ss相关的名单配置文件.
【2018年06月09日 21:35:15】: 重启dnsmasq服务...
【2018年06月09日 21:35:15】: 清除iptables规则和ipset...
【2018年06月09日 21:35:15】: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
【2018年06月09日 21:35:15】: +     发现你未开启Enable JFFS custom scripts and configs选项！     +
【2018年06月09日 21:35:15】: +    【软件中心】和【科学上网】插件都需要此项开启才能正常使用！！         +
【2018年06月09日 21:35:15】: +     请前往【系统管理】- 【系统设置】去开启，并重启路由器后重试！！      +
【2018年06月09日 21:35:15】: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
【2018年06月09日 21:35:15】: 插件将在5秒后自动关闭！！
【2018年06月09日 21:35:16】: 5
【2018年06月09日 21:35:17】: 4
【2018年06月09日 21:35:18】: 3
【2018年06月09日 21:35:19】: 2
【2018年06月09日 21:35:20】: 1
【2018年06月09日 21:35:21】: 0
【2018年06月09日 21:35:21】: 插件已关闭！！
【2018年06月09日 21:35:21】: ======================= 梅林固件 - 【科学上网】 ========================
 

虚拟内存和koolproxy可以正常运行

**Comment by MrCloudyGod** [comment]
同，不知道怎么解决，还是得刷回梅林了
