### ISSUE TITLE
GT-AC5300软件中心所有软件功能无响应

### ISSUE THREAD

**Issue by WangDePeng7** [koolshare/rogsoft#75]
GT-AC5300只有官改固件，为了科学上网和外部VPN访问刷入了该固件，每天都有自动断网和重新拨号的问题，然后通过系统Log查看原因，是因为每天遭受国外IP的攻击，被运营商踢掉了，然后才重新拨号，所以我就打开了【系统管理->系统设置->只允许特定IP访问】，这样只有内网的设备才能登陆路由器，也不会遭受到外网的攻击了，但是只要打开这个功能，软件中心装的软件都会出现问题。
比如：【科学上网】的【导出配置】不能用，更新软件不显示任何提示。所有的软件只要有提示的都不显示，而且，只要点击了不能用的功能，就要重新登录路由器才可以，不然会一直提示Loading。

**Comment by sadoneli** [comment]
被外网攻击的正确方式是关闭一些服务的外网访问，开启防火墙，更改服务端口，做一些端口转发等
而不是限定局域网内的登录IP，限定局域网这个是防内网的

因为软件中心是靠路由器内部的一个反向代理的工作（httpdb），如果你开启这个功能，就把反代也限定了，httpdb是软件中心的核心组件，不工作的话软件中心和所有插件自然就问题了
