### ISSUE TITLE
￥200 求购适用于AC86U官改的CloudFlare DDNS插件

### ISSUE THREAD

**Issue by DearTanker** [koolshare/rogsoft#76]

**Comment by sadoneli** [comment]
这么夸张，，，，我明儿来做吧，但是我没有cf的域名，不方便调试呢

**Comment by DearTanker** [comment]
@sadoneli 可以绑定一个过去试试呀，如果需要的话，我可以协助。

**Comment by DearTanker** [comment]
@sadoneli 或者你拿着这笔钱注册一个新域名用来测试，我可以先转你。

**Comment by sadoneli** [comment]
钱不需要的，我盲改个版本试试吧，不过今天384.9出来了，我得先弄固件

**Comment by DearTanker** [comment]
@sadoneli 明白，有在计划中就好了，我现在用二级路由器刷梅林来曲线更新DDNS，但是每次IP变更都得手动去点更新，2天左右丢得操作一次，在外面访问的时候很不方便。

**Comment by DearTanker** [comment]
是否有进展呢？

**Comment by DearTanker** [comment]
日思夜想，望眼欲穿。。

**Comment by DearTanker** [comment]
提到￥200吧，其他人有兴趣的话可以接单。谢谢了。
